### ISSUE TITLE
error

### ISSUE THREAD

**Issue by H1W0XXX** [johnspurlock/app-privacy-report-viewer#6]
PS Z:\> deno run --allow-net --allow-env --allow-read=.,which deno --allow-write=. https://raw.githubusercontent.com/johnspurlock/app-privacy-report-viewer/v0.7/src/app.ts

error: Cannot resolve module "file:///Z:/deno".

windows 10 64bit powershell

**Comment by H1W0XXX** [comment]
deno run --allow-net --allow-env --allow-write --allow-read https://raw.githubusercontent.com/johnspurlock/app-privacy-report-viewer/v0.7/src/app.ts

**Comment by johnspurlock** [comment]
It's true that example deno command tries to use minimal permissions, but depends on your shell.  I'll put a fallback command like yours into the docs as well.
